project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "Machine Learning Fundamentals"
            file:  Chapter_1_Challenge.html
          - text: "Supervised ML Challenge"
            file: content/01_journal/01_tidyverse.qmd
          - text: "temp"
            file: content/01_journal/05_automated_ML.qmd
          - text: "Automated ML with H20 (1)"
            file: content/01_journal/03_data_wrangling.qmd
          - text: "Automated ML with H20 (2)"
            file: content/01_journal/04_data_visualization.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto