---
title: "My Lab Journal"
subtitle: "Business Decisions with Machine Learning"
author: "Alexander Thiel"
---

The challenged can be accessed using the navigation menu above, or the links below. If the images are not displaying correctly, they can be found in the github folders under the file path given in the respective webpage.


# Machine Learning Fundamentals pdf.


::: callout-note
The html version can be accessed through the header. If it is not displaying correctly, the pdf can be viewed directly on github under the path "/content/01_journal/Chapter_1_Challenge.html"
:::

```{=html}
<iframe width="780" height="500" src="content/01_journal/Chapter_1_Challenge.html" title="Fundamentals Challenge"></iframe>
```


# Links to the Different Quatro Files

  [Supervised ML Challenge](content/01_journal/01_tidyverse.qmd)
  
  [Supervised ML Challenge copied to Quatro document](content/01_journal/challenge_1_backup.qmd)
  
  [Automated ML with H20 (1)](content/01_journal/03_data_wrangling.qmd)
  
  [Automated ML with H20 (2)](content/01_journal/04_data_visualization.qmd)

  [Performance Measures](content/01_journal/performance_tester.qmd)
  
  [Black Box Models](content/01_journal/blackBox_tester.qmd)
